import type { Metadata, Viewport } from "next";
import { Alegreya_Sans } from "next/font/google";
import "./globals.css";



const AlegreyaSans = Alegreya_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "300", "900", "800", "700"],
});

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#030712",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${AlegreyaSans.className}`}>{children}</body>
    </html>
  );
}
